### ISSUE TITLE
ページをリロードするとユーザーが切り替わってしまう

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#125]
## 発生している現象
- user1とuser2でそれぞれ別ウィンドウでログイン (user1の方を先にログイン)
- user1のウィンドウをリロードするとuser2にユーザーが切り替わる

## 原因に関する仮説

- user.controller.tsの中のgetLoginUserでRequestの中からUserを取り出している
- この、Requestに含まれるUserというものが一番直近でログインしたユーザーの情報に更新されてしまっている模様
- そのため、user1のあとにuser2がログインした状態で、user1のウィンドウで再度getLoginUserを呼び出すと、Requestから取り出したUserの情報はuser2になってしまっているのではないか

## 解決方法に関する仮説

- 最初にログインした際に、ユーザーIDを保存
- 再度ログインしているユーザーの情報をフロントエンドで取得したいときには、そのユーザーIDを使って、バックエンドの`user/:id`にGETリクエストを出してユーザー情報を取得 
- (要するに、ログインユーザーの情報を取得する際に、毎回Requestから取り出さないようにする)

**Comment by rakushoo** [comment]
ブラウザ内でsessionやCookieが共有されているのが原因かと思いました。

ボイチャで他のチームの方に聞いたところ、
* 課題要件として、別タブで異なるユーザーでの操作できるか否かは問われてない
* Chromeのシークレットウィンドウで別ユーザーの動作確認をしてる
という話がありました。

**Comment by takashi247** [comment]
情報共有ありがとうございます。
この話を聞いて改めて課題要件を読み直してみると、別タブで異なるユーザーでの操作ができるかどうかが求められていないからこそ、「Chrome以外に、もう一つのウェブブラウザでもアプリケーションを動かせること」というのが要件に入っているのかなと思いました。
なので、ローカルで2人のユーザーを操作してゲームができるかを確かめてもらう際には、片方はChromeでログインして、もう片方はFirefoxでログインしてもらって、対戦してもらえばよいのかと思いました。
ということで、このイシューは対応しなくてもいいかなと思うに至りました。
次の定例で相談させてください。
