### ISSUE TITLE
チャット画面からフレンドのプロフィールを表示できるようにする

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#139]
## 概要

- フレンドのプロフィールを表示できるようにする
- 既存のプロフィール画面と連携したい

**Comment by takashi247** [comment]
これ、現状のProfileコンポーネントのPropsにuserIdを渡したらそのユーザーのプロフィールが見られるようにしたら割ときれいに実装できる気がするので、私の方で対応します！
