### ISSUE TITLE
useQueryのキャッシュ処理について整理

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#154]
## 概要

現状useQueryを使って実装している部分のキャッシュの処理を統一して整理したい。

- `staleTime`, `cacheTime`をどのように設定するか
- エラーが起きたときに削除すべきキャッシュはどれか
- useQueryのonErrorの処理以外の場所でキャッシュを削除すべき箇所はあるか

## 参考リンク

- https://react-query-v3.tanstack.com/reference/useQuery
- https://medium.com/doctolib/react-query-cachetime-vs-staletime-ec74defc483e

**Comment by ryo-manba** [comment]
12/5  次回定例までに調べる(tnishina)

**Comment by takashi247** [comment]
## 結論

- 提出前にuseQueryUserも含めて、staleTime, cacheTimeの設定はなくしてしまっていいのではないか
(複数タブで別ユーザーでのログインができなくなるが、レビューの際には、Chrome/Chrome Incognito/Firefox/Firefox Incognitoで4ユーザー分は確保できるため問題ないのではないか)
- 'user'のキャッシュのみを削除しておけば、他のuseQuery/useMutationはuserモジュールのエンドポイントに対してのリクエストを投げるので、その時点でJWTトークンがないので無効になる
- エラー処理の中でログアウトさせる実装になっている部分については、全てキャッシュを削除する実装を追加すべき

## 参考資料

- https://zenn.dev/tokutsu/articles/54c8bfe31c8ee2
