### ISSUE TITLE
DashboardのFriendボタンの使い方について

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#155]
## 概要

ログインして最初に表示されるDashboard上のFriendボタンを押したときにどのようなページに遷移するかを議論したい

### 案①

- 現状、Friendボタンの先に実装されうる機能はすべてChat画面のFriendSidebarに実装されているという認識
- その場合、DashboardからFriendボタンを削除して、ChatボタンとGameボタンのみにしてしまってはどうか

### 案②

- 現在、Chat画面のFriendSidebarになっている部分をDashboardのFriendボタンを押下した際に遷移した先で表示されるようにしたらどうか
- その場合、Chat画面の右側のサイドバーには、現在FollowしているFriendリストのみを表示し、リストの中のFriendをクリックした場合には、すぐにそのFriendとのDMのやりとりが表示されるような形にしてはどうか

**Comment by ryo-manba** [comment]
12/5 定例で決定
Friendボタンを削除する
