### ISSUE TITLE
OAuthのログイン時にAPIを複数回呼ばないようにする

### ISSUE THREAD

**Issue by rakushoo** [ryo-manba/ft_transcendence#181]
現在、初回・ログイン時共に、index.tsxから/auth/oauthloginを複数回呼んでdashboardに遷移している。
ブラウザ上の見た目は問題ないが、2回目以降にcreateで例外が発生したり、そもそも何度も呼ぶ作りは直したい。

**Comment by takashi247** [comment]
~~おそらくこの問題は #248 を対応すると解決するのではないかと思います。備忘録までに記載しておきます。~~
↑これ、嘘でした。#248とは別で対応する必要がありそうです。
