### ISSUE TITLE
ゲーム中に一方のユーザーがブラウザバックしてもゲームが続く

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#207]
### 概要
対応するかどうかも含めて確認お願いします。

- ゲーム中に一方のユーザーがブラウザバックしてもゲームが続いています。
- 試合結果が反映されていますが、点数は変わっていません。

以下参照

https://user-images.githubusercontent.com/76232929/209417434-291e6f33-dd51-473b-aaa6-0845ff88ea31.mov

- ゲーム開始後に左側をブラウザバックしています。
- 試合終了後にリロードすると敗北が1増えていますが点数は反映されていません。
- 試合結果の画面で文字がかぶっています（17秒前後）

**Comment by ryo-manba** [comment]
試していませんが、ブラウザバック後に自分自身のゲームを観戦することもできてしまいそうですね。

**Comment by yuta-fujimoto** [comment]
* 点数が変わらないのはおそらくバグとして、
* ゲーム中に一方のユーザーがブラウザバックしてもゲームが続くに関しては、そもそも片方が接続切れたときに「something went wrong」とするのがいいのかあんまり知らない。(戦略的切断が可能)
* ブラウザバック後にゲーム観戦をすると普通にプレイできてしまう。。

ここらへん仕様決めてるのにしなさんなので月曜日にでも聞いてみたいです。

**Comment by takashi247** [comment]
ブラウザバックしたらエラーにしてsomething went wrongにしちゃえばいいかなと思います。点数更新されない問題や、ゲームを観戦できちゃう問題も、エラーで終了させれば解決する気がします。
対応してみます。
