### ISSUE TITLE
Next.jsをシングルページアプリケーションモードにする（要確認）

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#226]

**Comment by yuta-fujimoto** [comment]
SPAモードにする方法はどうとか書いてあるサイトもあったが、
https://zenn.dev/rinda_1994/articles/e6d8e3150b312d
と
https://gihyo.jp/book/2022/978-4-297-12916-3
の本のNextの章を見ている限りだと、

SPAはCSRのことで
`getServerSideProps, getInitialProps(SSR)`などを設定しているわけではないのだからそもそも今のままでSPAでは？
と思ったが、絶対かと聞かれるとよくわからない。。。

簡単に言うなら
* SPAはブラウザから直接バックエンドサーバに対してリクエストを送ってそのレスポンスによってページの見た目を更新するが、これは`frontend/api`ディレクトリ配下にある`axios`ライブラリなどを使って実装している。
というようなことが言えればとりあえずの説明としてはよいのではないか？

* SSRなどに関しては、複雑なので特にこちらからの言及は必要ない気がしてます。
