### ISSUE TITLE
SQL injectionsから守られていることを証明する（調査）

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#229]

**Comment by yuta-fujimoto** [comment]
SQLインジェクションとは(適当に追加していく)

https://www.shadan-kun.com/waf/sql_injection/
脆弱性のあるフォーム画面などに、SQL文の一部を入力して実行すると情報を漏洩させたり、データを破損させたりできる。

https://web-scan.jp/article/1868/
例えば、このサイトにやり方が書いてある。(多分すぐ読める)

`ft_transcendense` ではユーザ名変更で`new user'; DROP TABLE Users;--` とか入力してどうなるのか見るのがいいのかも
(`--`はそのあとコメントアウトするもので、最後の`'`を無視させる。)

**Comment by yuta-fujimoto** [comment]
どのように守られているのか？

* PrismaのPrepared Statement
https://zenn.dev/thirosue/books/49a4ee418743ed/viewer/ae5b9a
にある通り、prismaの`findUnique`などはprepared statementを用いてSQLを発行している。そうするとすでに定義されたSQLに対してパラメータを埋め込む形になるので例えば` tom' or '1'='1 `はそのまま文字列として認識されることになる。

* PrismaのEscape処理
https://zenn.dev/thirosue/books/49a4ee418743ed/viewer/ae5b9a#sql%E3%82%A4%E3%83%B3%E3%82%B8%E3%82%A7%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E7%A2%BA%E8%AA%8D%EF%BC%88native-query-%EF%BC%BB%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E6%8C%87%E5%AE%9A%EF%BC%BD-%EF%BC%89
`'`を`''`にしたり`\`を`\\`にしたりする。これは`findUnique`でうまくやれてるのか確認する必要がある。

* Nextの保護機能
https://zenn.dev/yuuhu04/books/xss-anti-pattern-of-react-and-vue/viewer/about-escapes
でescape処理するのか？あんまりわかってない。。

https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html#defense-option-4-escaping-all-user-supplied-input
これが一番、詳しいけど全部読むの大変。。。。

**Comment by yuta-fujimoto** [comment]
postgresのログを見る。
`ft_transcendence-dev-postgres-1` のコンテナで
1. su postgres
2. https://syutaku.blog/postgresql-log/
を参考にログの設定
3. pg_ctl restart

<img width="568" alt="image" src="https://user-images.githubusercontent.com/64348608/210303519-b1e35361-0def-4722-bc53-1b9baf5bbfa4.png">

* Prepared Statement
```
2023-01-03 05:10:44.486 UTC [78] LOG:  execute s69: SELECT "public"."User"."id", "public"."User"."createdAt", "public"."User"."updatedAt", "public"."Us
2023-01-03 05:10:44.486 UTC [78] DETAIL:  parameters: $1 = '2', $2 = '1', $3 = '0'
```

* Escape処理
```
DETAIL:  parameters: $1 = '...............'' or ''1''=''1', $2 = '1', $3 = '0'
```
$1の本来の入力は`キングダム' or '1'='1`

いったん終了
