### ISSUE TITLE
Ongoing Battelesの表示が崩れてる

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#233]
![image](https://user-images.githubusercontent.com/64348608/209679658-4d8d5b3d-cc24-4fda-a560-43cd7bafc265.png)

**Comment by ryo-manba** [comment]
お手すきで以下2点対応頂けると嬉しいです！（他の人が原因知ってる可能性もあるかもしれないので）
- どこがバグってるのか記載する（Ongoing Battelesの表示が崩れてるって話？）
- issueのタイトルで修正したいことを分かるようにする（ex：招待後に戻るボタンを押すと表示が崩れるバグの修正）

**Comment by yuta-fujimoto** [comment]
ありがとうございます、とりあえずOngoing Batteles表示崩れだけ直したいので題名だけ変えときました。

> もしかしたら、招待後に戻るボタン押すとバグるのかも

これはまだあんまり動作見てないのでまたあとで新しくissue必要であれば出しときます。

**Comment by yuta-fujimoto** [comment]
https://user-images.githubusercontent.com/64348608/209908693-b16e6e87-1c43-4528-86e7-137dd5bd2e72.mp4

まぁあんまり必要ないけど。。。
