### ISSUE TITLE
レビューに向けてVM上で正常に動くか確認する

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#239]
ft_transcendenceはクラスターのiMacかLinux VMでレビューすることになっている。
（参考: https://meta.intra.42.fr/articles/42cursus-remote2code)

**Comment by ryo-manba** [comment]
dockerfileで yarn をインストールする。
https://www.wakuwakubank.com/posts/307-javascript-yarn/

**Comment by ryo-manba** [comment]
ビルドは可能だが、以下のエラーが発生してしまう。
![スクリーンショット 2023-01-31 12 09 17](https://user-images.githubusercontent.com/76232929/215770364-09a64138-4df8-415a-818c-a6d0a3731a51.png)

**Comment by ryo-manba** [comment]
docker-composeのversionを上げる手順
- https://github.com/ryo-manba/ft_transcendence/issues/360

**Comment by rakushoo** [comment]
Ubuntuのアップデートを実施。18.04に更新。
docker-composeのアップデートを実施。
githubからcloneし、make。
(しばらく放置してから)FireFoxからhttp://localhost:3000へアクセスして、問題なく動作できました。
