### ISSUE TITLE
フロントエンドでエラー時の処理を共通化する

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#250]
## 概要

- 現状 `throw new Error` を使用していることが多い。

## 問題点

- 軽度のエラーでも度々クラッシュしたページが表示されてしまう。

## 対応案

対応案は2つあります。

### 1. Next.jsのエラーコンポーネントを返すようにする

- throwしている箇所を次のように置き換えて使用する。

```ts
return <Error statusCode={500} />
```
- 修正コスト高め
  - throwしている箇所をすべて書き換える必要があるため、修正行は多くなる。
- [参考](https://nextjs-ja-translation-docs.vercel.app/docs/advanced-features/custom-error-page#%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BF%E3%82%A8%E3%83%A9%E3%83%BC%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E5%86%8D%E5%88%A9%E7%94%A8)

### 2. Error Boundaryを利用して、まとめてエラー処理を行う

- 子コンポーネントでエラーが発生した際にクラッシュした UI の代わりに、フォールバック用の UI を表示させることができる。
- 修正コスト中くらい
  - ErrorBoundaryの導入をうまくできれば、既存のコードはそのままでいい。
- [参考](https://kudolog.net/posts/func-error-boundary/)

**Comment by ryo-manba** [comment]
他にいい案や、試してみたい方法などあればコメントいただけると助かります！

**Comment by takashi247** [comment]
@ryo-manba 
私が確認した限り、現時点のmainブランチのコードで、catchされていないためにクラッシュしうる`throw new Error`は以下の2点のみかと思います。

- frontend/pages/setting/index.tsxの144行目のhandleDialogClose関数中で使用されているchangeHas2FAMutation.mutateがエラーを投げた場合
- frontend/pages/setting/enable2fa.tsxの36行目のthrow new Error

他の部分は、例えばuseMutationの中でthrow new Errorしたりしていても、それを使っているコンポーネント内で全てcatchされていると思うのでクラッシュしないようになっているかと思います。
なので、上記の2箇所だけ個別対応すれば十分かと思うのですが、どうでしょうか？
もし勘違いしているところがあればご指摘ください。

**Comment by ryo-manba** [comment]
あーそうか、useMutation内のエラーは前言ってたやつですね！
ご指摘いただいた2点の修正のみで問題ないと思います！

**Comment by ryo-manba** [comment]
Next.jsのエラーコンポーネントを返すかまたはエラーメッセージを表示するくらいの対応で良さそうですね

**Comment by takashi247** [comment]
こちら、対応しておきます！
