### ISSUE TITLE
gameのProfileでアバター画像が出ない。

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#260]
こちらのほうでは、それ以外のところは出てました。

詳しく見てないですけど、
`frontend/components/game/home/Profile.tsx`の60行目の周辺の
```
  const avatarImageUrl =
    user.avatarPath !== null
      ? `${process.env.NEXT_PUBLIC_API_URL as string}/user/${user.avatarPath}`
      : '';
```
`${process.env.NEXT_PUBLIC_API_URL as string}/user/${user.avatarPath}`が正しいURLでない可能性がある。

個人的にどうするのがいいのかあんまりわかってないのでできたら確認お願いしたいです。

**Comment by yuta-fujimoto** [comment]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/64348608/211204117-d50335b4-ec0e-403e-b3cb-5f3500b63804.png">

**Comment by takashi247** [comment]
@yuta-fujimoto 
共有ありがとうございます。こちら、私の方で対応します。
