### ISSUE TITLE
作成済みのChatroomに入室すると過去のメッセージが二重に表示される

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#280]
## 概要

すでにメッセージのやり取りがあるChatroomに新しいユーザーが入室すると、そのChatroomで過去に送られたメッセージが二重にロードされてしまっているように見えます。

## Demo

https://user-images.githubusercontent.com/15176241/212500705-689c24c9-621e-44fc-ae08-c4fb63f44095.mov

**Comment by ryo-manba** [comment]
原因調査します！
