### ISSUE TITLE
フロントエンドに送るユーザー情報からsecret2FAを除くべきか

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#283]
## 概要

- 現状、useQueryUserを使って管理しているユーザー情報にはsecret2FAの情報が含まれている
- ちゃんと理解しきれていないが、このsecret2FAの情報って、2FAでログインする時のパスワードに当たる情報かと思うので、フロントエンドにユーザー情報を送る際にはOmitした方がいいのではないか？

## スクリーンショット

<img width="2032" alt="Screenshot 2023-01-15 at 10 44 21" src="https://user-images.githubusercontent.com/15176241/212508561-a72a3bc7-106b-4d08-8222-a540edd8801a.png">

**Comment by rakushoo** [comment]
こちらはfrontendで参照することはないので、hashedPasswordと同じくomitする方向で良いと考えています。
