### ISSUE TITLE
パスワード付きのルームへの入室失敗時にエラーが表示されない

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#299]
### 概要

- パスワード付きのルームへ入室をするときに誤ったパスワードを入力すると入室に失敗する
- 本来はエラー表示がされてほしいが、現状何も表示されていない

**Comment by ryo-manba** [comment]
~mainブランチだと正常にエラーメッセージが表示された。~
~以下のPRを修正する。~
~- https://github.com/ryo-manba/ft_transcendence/pull/279~

emitのack機能に書き換える際に、undefinedを返しているところが問題だった。

**Comment by ryo-manba** [comment]
そもそもemitに対するcallbackで、falsyな値は返せないかも？

> However, in this case, you won't be able to leverage interceptors. If you don't want to respond to the user, you can simply skip the return statement (or explicitly return a "falsy" value, e.g. undefined).

https://docs.nestjs.com/websockets/gateways

**Comment by ryo-manba** [comment]
試したみた結果として、 `null` と `undefined` のみ何も返してないと判定されることがわかった。

```ts
    socket.emit('chat:sample', 'hello', (res: any) => {
      console.log('chat:sample', typeof res, res);
    });
```

```ts
  @SubscribeMessage('chat:sample')
  async sample(
    @ConnectedSocket() client: Socket,
    @MessageBody() data: any,
  ): Response<any> {
    this.logger.log('chat:sample received', data);

    // それぞれコメント外して試す
    return 1;
    // return '1';
    // return { sample: 'sample' };
    // return false;
    // return null;
    // return undefined;
  }
```

**Comment by ryo-manba** [comment]
Gatewayにそれなりに手を加えてるので以下のissueからブランチ切って作業する
- https://github.com/ryo-manba/ft_transcendence/pull/279

**Comment by takashi247** [comment]
> 試したみた結果として、 `null` と `undefined` のみ何も返してないと判定されることがわかった。
> 
> ```ts
>     socket.emit('chat:sample', 'hello', (res: any) => {
>       console.log('chat:sample', typeof res, res);
>     });
> ```
> 
> ```ts
>   @SubscribeMessage('chat:sample')
>   async sample(
>     @ConnectedSocket() client: Socket,
>     @MessageBody() data: any,
>   ): Response<any> {
>     this.logger.log('chat:sample received', data);
> 
>     // それぞれコメント外して試す
>     return 1;
>     // return '1';
>     // return { sample: 'sample' };
>     // return false;
>     // return null;
>     // return undefined;
>   }
> ```

何も返してないと判定される、っていうのは、この場合だと`return undefined`か`return null`の場合には、フロントエンドのconsole.logが動かないってことですか？

**Comment by ryo-manba** [comment]
> 何も返してないと判定される、っていうのは、この場合だとreturn undefinedかreturn nullの場合には、フロントエンドのconsole.logが動かないってことですか？

そういう感じですね...。
何かを作成するメソッドの場合はobject or undefinedを返しているところがちらほらあるので、その辺を修正する必要がありそうです。

**Comment by takashi247** [comment]
うーん、なるほどですね。。。
今DM周りの修正をやっていて、まさに同じくobject or undefinedで実装しようとしてるところでした。。。
昨日共有してくれた、[このページ](https://docs.nestjs.com/websockets/exception-filters)に記載されてる方法を活用して、現在undefinedを返しているところでは、`throw new WsException('XXX')`を投げて、フロントエンドでは`socket.on('exception')`で受け取って、messageの内容を見て処理を書き分ける、っていう方法もあるかと思ったんですが、どうですかね？
WsException投げまくると、コードが読みづらくなりそうな気はしますが。。。

**Comment by takashi247** [comment]
もしくは、`return { sample: undefined };`とかにしたら、送れたりしますかね？？

**Comment by ryo-manba** [comment]
あ、もっとシンプルでいいのかなと思ってます。
具体的には2つの実装案を考えていました。

**1. socket.onでemitの結果を受け取る**
```ts
// 実際はuseEffectで設定する
socket.on('chat:createRoom', response);

socket.emit('chat:createRoom', data);
```

- emitでチャットルーム作成を実行
- 結果はsocket.onで受け取る
  -> undefinedの場合は、エラーメッセージ
  -> Chatroomの場合は、サイドバーにセットする


**2. 戻り値をkey valueオブジェクトにする**
こっちが本命です。
```ts
if (created)
  return { data: createdRoom }
return { data: undefined }
```
- 型を定義してあげるだけで対応できる。

**Comment by ryo-manba** [comment]
> もしくは、return { sample: undefined };とかにしたら、送れたりしますかね？？

これでいこうと思ってます!
