### ISSUE TITLE
オフラインのユーザーステータスがオンラインになっている

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#301]
### 概要

- オフラインのユーザーのステータスがオフラインになっている
- 本来user4のみログインしているが、その他のユーザーのステータスもオンラインになっている
<img width="284" alt="スクリーンショット 2023-01-17 11 50 23" src="https://user-images.githubusercontent.com/76232929/212799326-c0c050e9-395e-40d8-bb94-8f87dac407ff.png">

**Comment by takashi247** [comment]
@ryo-manba 
これ、もう少しこのbugが発生した時の状況を詳しく共有頂けないでしょうか？

- ログアウトしてるはずのユーザーはログアウトボタンでログアウトしたのか、ウィンドウを閉じてログアウトしたのか
- docker composeで動かしている時の挙動か、ローカルで動かしてる時の挙動か、など

様々な要因が考えられるので、分かる範囲で追加情報もらえるとありがたいです。

**Comment by ryo-manba** [comment]
> ログアウトしてるはずのユーザーはログアウトボタンでログアウトしたのか、ウィンドウを閉じてログアウトしたのか

~ウィンドウを閉じました！~
どちらも行っていました...。ログアウトもウィンドウを閉じるも。


> docker composeで動かしている時の挙動か、ローカルで動かしてる時の挙動か、など

ローカルでの挙動です！

**Comment by ryo-manba** [comment]
具体的な手順としては、

以下の手順でUserを増やす。
- userを10人くらい新たににregisterする（ログアウト -> registerを繰り返す）
- その後ウィンドウを閉じる

その後別で開いていたウィンドウでフレンド追加を行う
-> ログイン状態ではないのに、オンラインになっている。

**Comment by takashi247** [comment]
詳細ありがとうございます！よくわかりました。ちょっと調査してみます。

**Comment by takashi247** [comment]
@ryo-manba 
まだ調査中なのですが、おそらく、このバグが起きている原因としては、[このPR](https://github.com/ryo-manba/ft_transcendence/pull/183)を対応した際に議論した、ChromeとEdgeしか対応していなかったunloadというイベントに、いつの間にかChromeが対応しなくなってしまっていた、ということなのではないかと考えています。
念の為に、下記、確認して頂けないでしょうか。

- ChromeでもEdgeでも、右上のメニューのログアウトボタンを押した場合には、ちゃんとステータスもログアウトになる
- Edgeの場合は、タブを閉じただけでもログアウトになる
- Chromeの場合のみ、タブを閉じただけだとオンラインのままになる

**Comment by ryo-manba** [comment]
> 対応していなかったunloadというイベントに、いつの間にかChromeが対応しなくなってしまっていた、ということなのではないかと考えています。

これって何かサイトに記載されてたわけではないってことですよね？

**Comment by ryo-manba** [comment]
動作確認はnishinaさんの方では正常に動作したということでしょうか？

**Comment by takashi247** [comment]
私の手元だとChromeで、ログアウトボタンを押さずにタブを閉じたときだけ、オンラインのままになっています。

**Comment by takashi247** [comment]
> これって何かサイトに記載されてたわけではないってことですよね？

サイトに記載されてたというわけではないですね。実際の挙動をいろいろ試してみた結果という感じです。

**Comment by ryo-manba** [comment]
> 私の手元だとChromeで、ログアウトボタンを押さずにタブを閉じたときだけ、オンラインのままになっています。

同じ結果になりました。

**Comment by ryo-manba** [comment]
chromeとfirefoxで動かないとなると、他の方法を探してみるのが無難なんですかね。
