### ISSUE TITLE
Chatroomの情報をフロントエンドに送る時にhashedPasswordをOmitすべきか

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#304]
- 具体例としては、例えば、chat.gateway.ts中のstartDirectMessage関数の中で、`client.emit('chat:getJoinedRooms', rooms);`を行う際に、`rooms`にはhashedPasswordも含んだChatroomの情報が送られてしまっている
- User情報をフロントエンドに送る時と同様、Chatroom情報をフロントエンドに送る際にはhashedPasswordの情報はOmitした方がいいのではないか

**Comment by takashi247** [comment]
@ryo-manba 
本件、ご意見頂けるとありがたいです！

**Comment by ryo-manba** [comment]
これやります！issue起票ありがとうございます！
