### ISSUE TITLE
対戦開始のコンポーネント完成

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#31]
現状ある`Start.tsx`を進化させる形にする。
* Backend
デモで使っていた自分の名前など不要なデータのやり取りの削除、自分の名前はDBからとってくる。

* Frontend
ゲームっぽい画面になるようにというのとNext対応、バランスを見る必要があるので全体ができたらまた考える。

**Comment by takashi247** [comment]
このイシューなんですが、下記のイシューでやろうとしてることと重複する部分も結構ある気がするので、合わせて @yuta-fujimoto にお願いしちゃってもいいでしょうか？
- #18

**Comment by yuta-fujimoto** [comment]
@takashi247 
了解しました。そしたらやりますね
