### ISSUE TITLE
Chat/Profile/Setting画面にいる相手をinvite Gameしても通知が届かない

### ISSUE THREAD

**Issue by rakushoo** [ryo-manba/ft_transcendence#313]
別のPRを確認中に発生した現象です。
じっくり触れていなかったので既に検討済みの項目でしたらすみません。

* user1とuser2を新規登録。
* 両者ともchat画面へ
* user1からuser2をADD FRIENDで追加する。
* user1からuser2をInvite Gameする
* user2には通知がいかずゲーム開始できない

user2は、Profile,Settingの画面の時も同じく通知が来ませんでした。DashboardとGameの画面では通知は来ます。

**Comment by ryo-manba** [comment]
どのPRの確認中に発生しましたか？
ブランチを教えていただけると嬉しいです。

**Comment by yuta-fujimoto** [comment]
一般的にバグがあればどのブランチ(`main`でなければ)なのかの情報は欲しいですがこれに関しては大丈夫です。
いろんな画面で通知が出てもちょっと邪魔だな～と思ったので`Dashboard`と`Game`の画面だけにしてます！他も追加したほうが良ければご意見下さればすぐできます。

**Comment by rakushoo** [comment]
失礼しました。
@ryo-manba 
frontendでマイグレーション実行時にWarningが出ないように修正した #312
の確認中に発見したのですが、main でも同じ状況でした。

@yuta-fujimoto 
想定通り、ということで了解です。
Invite中に、DashboardやGame画面に移動したら通知が来たので、
「ユーザーが受け付けられる状態の時に届くようにしている」という仕様であればそのままでも良いと思います。

確認いただいて、リアクションのスタンプいただけたらクローズします。

**Comment by yuta-fujimoto** [comment]
了解しました！Closeお願いします。
@rakushoo

**Comment by rakushoo** [comment]
想定通りの動作だったため、問題ありません。クローズします。
