### ISSUE TITLE
DMを開始した際にjoinRoomが適切にできていない

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#319]
現状、DMを開始すると、画面上はcurrentRoomが切り替わるが、joinRoomがちゃんとできていないので、そこを修正する

**Comment by ryo-manba** [comment]
https://github.com/ryo-manba/ft_transcendence/pull/306/commits/71ce8d49ea574bb4b77d576c2d35453a016aa4b7 のコンフリクト修正によって、以下の処理が抜けちゃってますね。

https://github.com/ryo-manba/ft_transcendence/pull/279#pullrequestreview-1264589635

参考にしていただけるとー。

**Comment by ryo-manba** [comment]
あーこれ僕がミスってたので対応します...。

**Comment by takashi247** [comment]
> あーこれ僕がミスってたので対応します...。

お、なんと。すいません、ありがとうございます！！
