### ISSUE TITLE
ゲーム履歴の実装

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#33]
とりあえずDBのことは考えず、データを適当に準備しておく。

* 対戦相手
* スコア
* 勝ったか負けたか

の表示をさせる。

**Comment by takashi247** [comment]
後ほどWIPのプルリクドラフトを上げますが、GameRecordは下記のようなモデルで行こうかと思っています。
isPlayingがtrueのものを引っ張ってくると、Watchコンポーネントに表示するリストが作れるような感じにできないかな、と思っています。
取り急ぎ状況の共有まで。

![image](https://user-images.githubusercontent.com/15176241/199064618-5ed67059-1e64-45c7-b2dc-c60f6bf67755.png)
