### ISSUE TITLE
依存変数が省略されているuseEffectのチェック

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#334]
- 現状、いくつかのuseEffectにおいて、依存変数が完全に省略されている事例が散見される (= `[]`も指定されていないようなケース)
- [このリンク](https://stackoverflow.com/questions/57760842/why-would-we-use-useeffect-without-a-dependency-array)の記述を踏まえると、`[]`を省略すべきケースは割と限定的な気がするので、本当に省略されていていいのか、チェックしたい

**Comment by ryo-manba** [comment]
これは対応したほうが良いですね...。
