### ISSUE TITLE
DMに第三者が入室できてしまう

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#336]
https://user-images.githubusercontent.com/64348608/214062947-3f1cd2a9-f094-468b-ad0c-da37cfba0ac4.mp4

`main`で確認したのでリロードしないとメッセージ送れないですね。`fix-direct-message`も第三者が入室できることについては同じです。

**Comment by yuta-fujimoto** [comment]
@ryo-manba 
すみませんが、対応するかも含めてご確認お願いできますか？

**Comment by ryo-manba** [comment]
SearchRoomに表示しないように変更します！
