### ISSUE TITLE
ユーザーのアバターイメージが物理的に削除されるとログインが行えなくなる

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#356]
### 概要

- 原因わかってないですが、`<Error statusCode={500} />` を返すようにしたいです。
- タブを閉じてもエラーが続いてしまうのは結構問題ありそうですね。

### 再現手順
1. プロフィール画像を登録する
2. backend/uploads/avatarImages/ を削除する
3. プロフィール画像を変更する -> エラーが出る
  - chatページに行くとずっとリロードになる
  - gameページに行くとフェッチエラーが表示される
  - logoutが反応しない（実行されるがエラー表示が出ない）
4. タブを閉じて、再度ログイン画面にアクセスする
5. ログインが行えなくなる

**Comment by rakushoo** [comment]
私の環境だと、backend側のログに[ExpressAdapter]のエラーログが吐かれます。
（make f, make b で起動）
chatページ、gameページにも遷移できますが、同じログが出て、
画面上はデフォルトの画像が表示されます。

[Nest] 63528  - 2023/01/29 20:42:08   ERROR [ExpressAdapter] ENOENT: no such file or directory, open '...XXX/backend/uploads/avatarImages/8cd6e6a1-fbf2-4de1-ad39-39c6e48aa13d.png'

先ほど、追加で実装していただいた画像が見つからない時はデフォルト画像にする変更は反映されてますか？
