### ISSUE TITLE
tailwind関連のファイル・コードを削除していいか確認

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#365]
tailwindは使っていない気がするので下記のものは削除してしまっていいかと思ってますが、もし自分の担当範囲でtailwind使っている、という方がいたら教えてもらいたいです。

- frontend/tailwind.config.js
- package.jsonの中のtailwind関連のパッケージ
- postcss.config.js内のtailwindに関する記述
- globals.css内のtailwindに関する記述

**Comment by ryo-manba** [comment]
ところどころでtailwind使ってます！
こんな感じでclassNameでスタイル書いてるやつはそうですね。
https://github.com/ryo-manba/ft_transcendence/blob/main/frontend/components/chat/chatroom/ChatroomSettingDetailDialog.tsx#L32

そのため、こちらはそのままにしていただけると嬉しいです！
