### ISSUE TITLE
Googleログイン時のtrans_testという表示をft_transcendenceにしたい

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#367]
### 概要

- Googleログイン実行時に `trans_test` と表示される
- `ft_transcendence` にしたい

![スクリーンショット 2023-01-31 17 49 45](https://user-images.githubusercontent.com/76232929/215712953-c842e191-b1d7-442a-8639-d6c9722ef357.png)

**Comment by ryo-manba** [comment]
@rakushoo 
こちらの対応可能でしょうか？
修正コスト高いようであればそのままで大丈夫です！

**Comment by rakushoo** [comment]
コストかかりませんので直しておきました！
@ryo-manba ご確認の上、クローズしていただいても良いでしょうか？
![スクリーンショット 2023-01-31 22 08 37](https://user-images.githubusercontent.com/2654860/215768437-1c0593a3-b34a-4679-98d2-acf7de8ede1a.png)

**Comment by ryo-manba** [comment]
対応ありがとうございます！
確認しましたのでこちらクローズとします。
