### ISSUE TITLE
OAuthログインでdashboardに遷移できない

### ISSUE THREAD

**Issue by rakushoo** [ryo-manba/ft_transcendence#372]
どこかのタイミングで/auth/oauth-loginを2回呼ぶようになり、
backendからfailureが返ることでログインに失敗しています。

方針としては、フラグを立てて、/auth/oauth-loginを実行中にさらに呼び出さないような対策をしてみます。

**Comment by rakushoo** [comment]
useEffectで[status,session,debug,router]→[status]に戻したら解消されました。
PRのレビュー時には気づかずすみません。

そのうち、sessionが更新されて呼ばれてしまうみたいなので、やはり/auth/oauth-loginを2回呼ばない仕組みにします。

**Comment by rakushoo** [comment]
原因がわかりました。

* OAuthの認証後、frontの/authに遷移し、useEffectが[status,session...]により複数回呼ばれる。
* backendの/auth/oauth-login を複数回呼ぶと、loginUserIds.findで同じuser.idへのログイン時はExceptionを発行する
* frontendへfailureを返すことになり、signOut("/");してしまう。

相談：  
backendの/auth/oauth-loginについて、
* 何度呼んでも大丈夫（副作用なし）にして良いか、
* front側から1回しか呼ばない仕組みにすべきか、
どちらが良さそうでしょうか？

**Comment by takashi247** [comment]
> 何度呼んでも大丈夫（副作用なし）にして良いか

この部分がどのような実装にすることを想定されているのかわからないですが、useEffectを使わない、ということをおっしゃっているのであれば、それはやめた方がいいと思います。
前のPRの際に提案した、フラグを使った方法で1回した呼ばない仕組みにできるようなら、そうした方がいいと思います。

**Comment by yuta-fujimoto** [comment]
@rakushoo 
https://github.com/ryo-manba/ft_transcendence/pull/358

すみません、こちらで現在修正中です。早めにissue立てるべきでした。
現在、`oauth-login`が複数回呼ばれることの対策として、二つの方法を使っていて

* ログイン成功時に`socket.connect()`を呼んで
```
      if (socket.disconnected) void loginAfterOAuth();
```
とすることで、二回呼ばれないようにする

* `ValidationDialog`が開いているとき(ログインが成功していて2FAの入力中)には、いかなるエラーメッセージが来てもリダイレクトをキャンセルする。

基本的に一個目の方法で防げますが、OAuth => 2FA => ログイン画面 を素早く繰り返すとなぜかエラーが出てしまっているので二個目もつけてます。

あんまりきれいな方法でもないので、何かアイデアがありましたら教えていただけると助かります。
