### ISSUE TITLE
チャネルオーナーはチャネルAdminもban/muteできるようにする

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#388]
- レビュー項目だと、`A user who is an owner of a channel can kick, ban, mute other users and the channel administrators.`となっているので、**オーナーはadminもban/muteできるようにした方が良さそう**。
- またAdminについては、`A user who is an administrator of a channel can kick, ban mute other users, but not the channel owners.`となっており、adminがオーナーをban/muteはできないとはなっているが、**adminが別のadminをban/muteすることは禁止されていない**ので、できるようにした方が良さそう

**Comment by ryo-manba** [comment]
ban/muteされたadminの権限は剥奪する予定ですか？
しない場合は、歯車アイコンからban/muteできてしまうので、挙動が不自然になるかもと思いました。

**Comment by takashi247** [comment]
> ban/muteされたadminの権限は剥奪する予定ですか？

そうですね、その予定です。

**Comment by ryo-manba** [comment]
あと1点追加でお願いです。
ban/mute.serviceそれぞれ実行前にオーナーを探すメソッドを使用して、ban/mute実行前にオーナーでないことを確認していただいてもよろしいでしょうか。DIでchatroom.serviceを追加するような感じをイメージしてます。
https://github.com/ryo-manba/ft_transcendence/blob/main/backend/src/chat/chatroom.service.ts#L142-L150

**Comment by ryo-manba** [comment]
現状だと、以下の手順で不整合が発生してしまいます...。（自分のミスです）
- user1: owner
- user2: admin
- user3: normal

user2がuser3をbanする。
そのタイミングでuser1が退出、user3をownerに指名する。

バックエンドで防いでないので、user3がbanされてしまう。
結果、ownerがルームに入れない。

**Comment by takashi247** [comment]
なるほどですね。。。まだほとんど実装していないので、もし可能であれば、このイシュー、まつかわさんにお渡ししてもいいですか？
もしこっちをやっていただけるようであれば、私はkickとChatにOngoing Gamesを追加する方を実装しちゃおうかと思っています。
(明日の夜までにnopさんからの返信が来る保証がないので、そこまで手間でもないから実装しちゃった方がいいかと)

**Comment by ryo-manba** [comment]
了解です！自分やりますね！
kickと観戦追加の件よろしくお願いします！

**Comment by rakushoo** [comment]
@ryo-manba 
先ほど課題が修正され、「ban,kickはadminだけでオーナーはできない」方向になりました。
せっかく対応していただいたのですが、入れなくて良いかもしれません。

![2023-02-10_12 40 26](https://user-images.githubusercontent.com/2654860/217998263-7f9d27e4-1793-4ae4-9ccb-814539dd64bf.png)

**Comment by takashi247** [comment]
@rakushoo 
`but not the channel owners.`というのは「オーナーがban、kickをできない」という意味ではなく、「Adminがオーナーをban, kickできない」という意味だと思うので、今まつかわさんにPR出してもらっている通りに修正した方がよい、というのは変わらないかと思いますが、どうでしょうか？

**Comment by takashi247** [comment]
またそもそも課題文でも「チャネルオーナーはチャネルAdminである」という一文があるので、Adminができる、ということはオーナーもできる、ということになるかと思います。

**Comment by rakushoo** [comment]
but notは、an administrator of channel ではなく、other usersにかかってるということですね。。
大変失礼しました。
