### ISSUE TITLE
baseUrlを設定して相対パスを絶対パスに統一する(frontend)

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#39]
### 概要
- 相対パスを使うとファイルの位置が分かりづらいので絶対パスにしたい

### やること
- baseUrlをsrcにする
- 既存のコードで相対パスを使用しているものを絶対パスに置き換える

[参考]
https://zuma-lab.com/posts/typescript-import-absolute-path-settings

**Comment by yuta-fujimoto** [comment]
@ryo-manba 
相対パス長々と使ってるの現状僕なのでやってもいいですか？

**Comment by ryo-manba** [comment]
@yuta-fujimoto 
ありがとうございます！お願いします！

**Comment by ryo-manba** [comment]
NestJSは別issueで対応します
