### ISSUE TITLE
DMで追加されたユーザー側にメッセージが表示されない

### ISSUE THREAD

**Issue by rakushoo** [ryo-manba/ft_transcendence#399]
# 環境
VM、firefoxで確認された現象です。
MacOS、Chromeでは、不具合は発生しない。
MacOS、firefoxでは、ウィンドウ2つ開くとYou can't log in with multiple windows/tabs.でログインさせない。
MacOS、firefoxで、user1と42アカウントではログイン可能。不具合は発生しない。

# 現象
ユーザー間でDMを送る時、片方にしか表示されない

# 手順
* user1とuser2でログイン
* user1がuser2をfriend登録。（user2にはuser1は表示されない）
* user1がuser2にDirectMessageを送ろうとするとRoomができる（user2側にroomが表示されないことがある）
（この時、user1にはuser2と表示したルームが、user2側にはuser1と表示したルームができる）
* それぞれメッセージを送ると、user1側しか表示されず、user2にはメッセージが見えない。送受信はできてる。
* 再度ログインするとそれまでのメッセージは正常に表示されるが、その後メッセージを送っても、user1側だけ追加したメッセージが表示され、user2側は画面が更新されない。リロードすれば全て表示される。

https://user-images.githubusercontent.com/2654860/219817652-072ae39b-30c7-4d1c-83ec-1789eaaea665.mov

# 試してて感じたこと
user1からuser2にフレンド設定→DMを送信の場合、メッセージが発生したときにuser2側の画面更新が届いてないように見えます。user2からメッセージを送る時も、user1側の画面だけ更新され、user2側は画面が更新されない（自分の今送ったメッセージが表示されない）です。
何かヒントにならないでしょうか？

前半はうまく行くが、再度Home→chatになった時に不具合が発生する動画
https://user-images.githubusercontent.com/2654860/219819154-d5e364ae-3a0c-4bf3-8843-b7ced6ad99cd.mov

![スクリーンショット 2023-02-18 9 00 24](https://user-images.githubusercontent.com/2654860/219819207-7492098f-25af-4ad5-8243-246d5c67c2dc.png)

**Comment by yuta-fujimoto** [comment]
多分VMだけで起きてる問題ですよね。。。
以前あったのはソケットが接続できてないというのがありました。
接続できているかどうかは
```
socket.connected
```
(socketはsocket.ioのソケットインスタンス)というフラグで確認ができてたはずです。ただ今までのレビューは普通にできてたのでちょっと謎です。。

**Comment by takashi247** [comment]
@yuta-fujimoto ゆうたさんの環境でも同じ問題が起きてる感じですか？

**Comment by yuta-fujimoto** [comment]
いや、vm僕の方も動かなくてローカルでやってたんですが確認できなかったのでそういうことだろうと言う感じです。
あした、すぐ見ます

**Comment by takashi247** [comment]
@rakushoo 可能であればスクショじゃなくて動画でアップロードしてもらった方がありがたいです。このスクショに至るまでの過程も理解したいです。

**Comment by rakushoo** [comment]
前半はうまく行くが、再度Home→chatになった時に不具合が発生する動画
https://user-images.githubusercontent.com/2654860/219819032-dd6ffdc7-6e0b-4e8e-b54c-09c9115a2c26.mov

ログも表示させてみましたが、うまくいかない時はソケットのエラーが出ています。


![スクリーンショット 2023-02-18 9 00 24](https://user-images.githubusercontent.com/2654860/219819074-6f5039a0-bb20-4bf9-a3af-62ad4d008d74.png)
