### ISSUE TITLE
Loggerを全体で統一しても良いかの調査

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#43]
### 概要

- loggerをbackend全体で統一したものを使うか、それともモジュールごとに作成するかを決める
- どっちがいいかをざっと調査する

参考
https://docs.nestjs.com/techniques/logger

**Comment by ryo-manba** [comment]
https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging
ドキュメントに以下の記載がありました。
> A good practice is to instantiate Logger class from @nestjs/common in each of our services.

要は、各サービスごとに@nestjs/commonからLoggerクラスをインスタンス化したほうが良いって感じですね。

**Comment by ryo-manba** [comment]
こんな感じで、それぞれ使うタイミングでインスタンス化しましょう

```typescript
import { Logger, Injectable } from '@nestjs/common';

@Injectable()
class MyService {
  private readonly logger = new Logger(MyService.name);

  doSomething() {
    this.logger.log('Doing something...');
  }
}

```

**Comment by yuta-fujimoto** [comment]
了解しました。調査のほうありがとうございました。
