### ISSUE TITLE
画面遷移図のたたき台

### ISSUE THREAD

**Issue by rakushoo** [ryo-manba/ft_transcendence#56]
draw.io で簡単な画面遷移を作成しました。

チームへの招待リンク
https://miro.com/welcomeonboard/RzNFS0xQQzBUdTRFWDFPYjN1bWNsemdYbG45MmZnMHZjTllIRHpRMktuUTFaTERlbFFQVktnOHlGTm44dHJYdHwzMDc0NDU3MzQ4NjE1Njg0NDU3fDI=?share_link_id=923306915377

参照のみ（非登録会員の編集は有料プランかららしい）
https://miro.com/app/board/o9J_lbYM-4o=/?share_link_id=947232855041

![スクリーンショット 2022-10-30 11 02 54](https://user-images.githubusercontent.com/2654860/198859254-c1bbfab7-d91f-49e8-bce4-eab6c073def4.png)

**Comment by takashi247** [comment]
早速ありがとうございます！
miroですが、[学生用のfree plan](https://help.miro.com/hc/en-us/articles/360017730473-Education-plan#:~:text=Miro%20provides%20the%20free%20Educational,and%20students%20of%20educational%20institutions.)があるようなので、42 Tokyoのメアドで取得できないか、トライしてみます。
また進捗アップデートします。

**Comment by ryo-manba** [comment]
> 参照のみ（非登録会員の編集は有料プランかららしい）

自分無料プランで利用していますが、編集できました！(学生用のfree planではない)

**Comment by takashi247** [comment]
なるほどですね、登録さえしてれば、無料プランでも編集できる、ってことですね！共有ありがとうございます！
