### ISSUE TITLE
全体で共有するAppBarをつくる

### ISSUE THREAD

**Issue by yuta-fujimoto** [ryo-manba/ft_transcendence#59]
簡単なユーザ情報の表示、ホーム画面遷移、ログアウトなどをするbarを上部に付けたいです。

実装するべきかどうかお聞きしたいので議論にしておきます

**Comment by ryo-manba** [comment]
https://github.com/ryo-manba/ft_transcendence/pull/51 でだしてる、barを共通で使えるように配置しておきます
