### ISSUE TITLE
GameRecordのDB改良

### ISSUE THREAD

**Issue by takashi247** [ryo-manba/ft_transcendence#67]
# 概要
下記の点を含む、GameRecordのDB改良を実施
- winnerName/loserNameにuserIdを紐付けて記録
- ~~(要相談) createdAtの時間を日本時間に変更~~バックエンドは時間を調整せず標準時で記録

**Comment by yuta-fujimoto** [comment]
@takashi247 
質問なんですが、userIdを付けた後ってloserName, winnerNameは消しますか？(recordを取得する際はJOINする)

**Comment by takashi247** [comment]
> @takashi247 質問なんですが、userIdを付けた後ってloserName, winnerNameは消しますか？(recordを取得する際はJOINする)

DB設計のいろはがわかっていないので何とも言えないのですが、最小限のデータだけ保持させるのであれば、userIDだけ保持して、名前がほしいときにはuserIDをベースにUserデータベースに名前のデータを取りに行くのが望ましい気がしますね。
まぁただ、そんな巨大なDBになるわけでもないし、時間に余裕があったら修正する形にして、一旦loserName, winnerNameを残したままで実装しちゃっていいかなと思いました。

**Comment by ryo-manba** [comment]
なんとなくですが、必要な要素は以下になるのかなという気がしてます。

```
[GameRecord]
winnerId:    Int
loserId:     Int
winnerScore: Int
loserScore:  Int
```

名前で保存してしまうと、同姓同名の場合に集計がややこしくなりそうな感じがしますね。。

**Comment by takashi247** [comment]
> 名前で保存してしまうと、同姓同名の場合に集計がややこしくなりそうな感じがしますね。。

確かに。やっぱidで照合しないとだめっすね。
@yuta-fujimoto やはり名前は消して、idのみ残す感じですね。また追って相談させてください。

**Comment by yuta-fujimoto** [comment]
名前はユーザ名そのまま使う予定のはずなんですが、ユーザ名って重複しないんじゃなかったでしたっけ、、？
subjectにそんなようなことが書いてあったような

**Comment by ryo-manba** [comment]
たしかに。ユーザー名の重複はしませんでした。。

ですが、それでもidでやったほうが良いような気はしますね。
chatRoom、UserをMessageに紐づけるときに以下のようにしてます。
https://github.com/ryo-manba/ft_transcendence/blob/main/backend/prisma/schema.prisma#L31-L32


nishinaさんがおっしゃるとおり、名前を表示するときにidから取ってくるとかでいいんじゃないですかね。(ひと手間増えちゃいますが)
```
const 勝者 = findUnique(winnerId)
const 敗者 = findUnique(loserId)
```

**Comment by yuta-fujimoto** [comment]
あんまり面倒なことはしなくてもよさそうですね、知らなかったです。それならidにしてもいい感じもします！
