### ISSUE TITLE
yarn installすると@types/yupが入ってしまう問題調査

### ISSUE THREAD

**Issue by ryo-manba** [ryo-manba/ft_transcendence#96]
### 概要

- yarn installするとpackage.jsonに@types/yupが入る
- しかし、事前にpackage.jsonに追加するとビルドエラーになるので、原因を調査する

**Comment by takashi247** [comment]
YupをZodに置き換える形で解決できないか検討。
(参考URL: https://github.com/react-hook-form/resolvers)
